import type { Metadata } from "next";
import "./globals.css";
import { satoshi } from "../../public/fonts/satoshi";
import ScrollToTop from "@/utils/scrollToTop";
import ReduxProvider from "@/redux/provider";
import { Toaster } from "react-hot-toast";
import CartMobileBar from "@/components/common/cart/CartMobileBar";
import NextAuthProvider from "@/components/NextAuthProvider";
import GoogleAuthHandler from "@/components/auth/GoogleAuthHandler";
import PhoneNumberCheck from "@/components/auth/PhoneNumberCheck";
import CustomToaster from "@/components/common/CustomToaster";

export const metadata: Metadata = {
  title: "Alpha Art & Events",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={satoshi.variable}>
      <body className="font-satoshi">
        <NextAuthProvider>
          <ReduxProvider>
            <GoogleAuthHandler />
            <PhoneNumberCheck />
            <ScrollToTop />
            {children}
            <CartMobileBar />
            <CustomToaster />
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
